### ISSUE TITLE
(Recommended) Remove your pet's blood count display

### ISSUE THREAD

**Issue by Omgise** [quentin452/Mo-Creatures-Continuation#10]
I don't think that health bar looks very nice

**Comment by quentin452** [comment]
wtf is that thing :D

**Comment by quentin452** [comment]
is it possible to give a screenshot of this?

**Comment by Omgise** [comment]
Of course you can :)

**Comment by Omgise** [comment]
![image](https://github.com/quentin452/Mo-Creatures-Continuation/assets/106000018/cd131bd1-db76-49b3-860c-5bfbd0da074a)

**Comment by quentin452** [comment]
it seem thats added by an another mod

**Comment by quentin452** [comment]
![Capture d’écran_2023-12-03_15-24-26](https://github.com/quentin452/Mo-Creatures-Continuation/assets/42176772/ea57c664-c760-4ce9-95a5-9baeac0eb2cd)
i don't have this display

**Comment by Omgise** [comment]
You need to tame this goat, please try to feed it apples :D

**Comment by quentin452** [comment]
ah ok i see :D

**Comment by quentin452** [comment]
so you mean it would be a good thing if only the pet name is displayed?

**Comment by Omgise** [comment]
Yes, because it will block the Neat module's health bar from each other

**Comment by quentin452** [comment]
it doesn't exist in the original mod?

if it doesn't , i am pretty sure thats been added by jss2a98aj

**Comment by quentin452** [comment]
but l'ill make something for this

**Comment by Omgise** [comment]
I never used the original mod because I heard it was buggy

**Comment by Omgise** [comment]
Or whether it is possible to add a configuration to turn it off

**Comment by quentin452** [comment]
global-settings {
    # Allows you to instantly spawn MoCreatures from GUI.
    B:allowInstaSpawn=false

    # Animate Textures
    B:animateTextures=true

    # Turns on verbose logging
    B:debug=false

    # Shows Pet Health
    B:displayPetHealth=true

    # Shows Pet Emotes
    B:displayPetIcons=true

    # Shows Pet Name
    B:displayPetName=true

    # If true, it will force despawns on all creatures including vanilla for a more dynamic experience while exploring world. If false, all passive mocreatures will not despawn to prevent other creatures from taking over. Note: if you experience issues with farm animals despawning, adjust despawnLightLevel. If CMS is installed, this setting must remain true if you want MoCreatures to despawn.
    B:forceDespawns=false
    I:particleFX=3
}

**Comment by Omgise** [comment]
Then this problem should be closed, I know this can be adjusted.  XD

**Comment by quentin452** [comment]
yes i think this could be closed
