### ISSUE TITLE
MoCreatures.cfg not working

### ISSUE THREAD

**Issue by xronin01** [quentin452/Mo-Creatures-Continuation#11]
I put it all in false and it keeps spawning
[latest.log](https://github.com/quentin452/Mo-Creatures-Continuation/files/13628138/latest.log)

# Configuration file

####################
# ant
####################

ant {
    B:canspawn=false
    I:frequency=7
    I:maxchunk=4
    I:maxspawn=4
    I:minspawn=1
}

####################
# bear
####################

bear {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=4
    I:maxspawn=2
    I:minspawn=1
}

####################
# bee
####################

bee {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# bigcat
####################

bigcat {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=4
    I:maxspawn=2
    I:minspawn=1
}

####################
# biggolem
####################

biggolem {
    B:canspawn=false
    I:frequency=3
    I:maxchunk=1
    I:maxspawn=1
    I:minspawn=1
}

####################
# bird
####################

bird {
    B:canspawn=false
    I:frequency=15
    I:maxchunk=4
    I:maxspawn=3
    I:minspawn=2
}

####################
# boar
####################

boar {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=2
}

####################
# bunny
####################

bunny {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=4
    I:maxspawn=3
    I:minspawn=2
}

####################
# butterfly
####################

butterfly {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=3
    I:minspawn=1
}

####################
# crab
####################

crab {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# cricket
####################

cricket {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# crocodile
####################

crocodile {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# deer
####################

deer {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# dolphin
####################

dolphin {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# dragonfly
####################

dragonfly {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# duck
####################

duck {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# elephant
####################

elephant {
    B:canspawn=false
    I:frequency=4
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# ent
####################

ent {
    B:canspawn=false
    I:frequency=4
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# firefly
####################

firefly {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# fishy
####################

fishy {
    B:canspawn=false
    I:frequency=12
    I:maxchunk=6
    I:maxspawn=6
    I:minspawn=1
}

####################
# flamewraith
####################

flamewraith {
    B:canspawn=false
    I:frequency=5
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# fly
####################

fly {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# fox
####################

fox {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=2
    I:maxspawn=1
    I:minspawn=1
}

####################
# goat
####################

goat {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=2
    I:maxspawn=3
    I:minspawn=1
}

####################
# hellrat
####################

hellrat {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=4
    I:maxspawn=4
    I:minspawn=1
}

####################
# horsemob
####################

horsemob {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=3
    I:minspawn=1
}

####################
# jellyfish
####################

jellyfish {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=4
    I:maxspawn=4
    I:minspawn=1
}

####################
# kitty
####################

kitty {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# komododragon
####################

komododragon {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# maggot
####################

maggot {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# mediumfish
####################

mediumfish {
    B:canspawn=false
    I:frequency=10
    I:maxchunk=4
    I:maxspawn=4
    I:minspawn=1
}

####################
# minigolem
####################

minigolem {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=2
    I:maxspawn=1
    I:minspawn=1
}

####################
# mole
####################

mole {
    B:canspawn=false
    I:frequency=7
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# mouse
####################

mouse {
    B:canspawn=false
    I:frequency=7
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# ogre
####################

ogre {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# ostrich
####################

ostrich {
    B:canspawn=false
    I:frequency=4
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# piranha
####################

piranha {
    B:canspawn=false
    I:frequency=4
    I:maxchunk=4
    I:maxspawn=3
    I:minspawn=1
}

####################
# raccoon
####################

raccoon {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# rat
####################

rat {
    B:canspawn=false
    I:frequency=7
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# ray
####################

ray {
    B:canspawn=false
    I:frequency=10
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# scorpion
####################

scorpion {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# shark
####################

shark {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# silverskeleton
####################

silverskeleton {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=4
    I:maxspawn=4
    I:minspawn=1
}

####################
# smallfish
####################

smallfish {
    B:canspawn=false
    I:frequency=12
    I:maxchunk=6
    I:maxspawn=6
    I:minspawn=1
}

####################
# snail
####################

snail {
    B:canspawn=false
    I:frequency=7
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# snake
####################

snake {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# turkey
####################

turkey {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=2
    I:maxspawn=2
    I:minspawn=1
}

####################
# turtle
####################

turtle {
    B:canspawn=false
    I:frequency=6
    I:maxchunk=3
    I:maxspawn=2
    I:minspawn=1
}

####################
# werewolf
####################

werewolf {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=4
    I:minspawn=1
}

####################
# wildhorse
####################

wildhorse {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=4
    I:maxspawn=4
    I:minspawn=1
}

####################
# wraith
####################

wraith {
    B:canspawn=false
    I:frequency=1
    I:maxchunk=3
    I:maxspawn=1
    I:minspawn=1
}

####################
# wwolf
####################

wwolf {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=3
    I:minspawn=1
}

####################
# wyvern
####################

wyvern {
    B:canspawn=false
    I:frequency=8
    I:maxchunk=3
    I:maxspawn=3
    I:minspawn=1
}

**Comment by quentin452** [comment]
the issue appear with the original mod?

**Comment by quentin452** [comment]
it seem yes

**Comment by xronin01** [comment]
I tested the new version and it keeps spawning!

**Comment by xronin01** [comment]
[latest.log](https://github.com/quentin452/Mo-Creatures-Continuation/files/13629775/latest.log)

**Comment by quentin452** [comment]
for me it stopped from spawning

**Comment by quentin452** [comment]
then wontfix

**Comment by xronin01** [comment]
What

**Comment by xronin01** [comment]
I'll try to put "frequency=0"

**Comment by quentin452** [comment]
i put all configs to 0 and false and entities continue to spawn

**Comment by quentin452** [comment]
I have an idea to fix the issue , but i need to rewrite the whole config , so i think it will take to me some hours to make

**Comment by xronin01** [comment]
I just noticed that the roach is not included in the config file

**Comment by xronin01** [comment]
It's good to check if there are more mobs missing

**Comment by quentin452** [comment]
the entity roach?

**Comment by xronin01** [comment]
> a entidade barata?

Yes

**Comment by quentin452** [comment]
and yes Roach doesn't exist in the mocEntityMap , so l'ill add it

**Comment by quentin452** [comment]
[unzipme.zip](https://github.com/quentin452/Mo-Creatures-Continuation/files/13630775/unzipme.zip)

This rewrite should work well , pls resset MoCreatures.cfg
