### ISSUE TITLE
Very strange crash with mc arrow and Werewolf mocreatures

### ISSUE THREAD

**Issue by kotmatross28729** [quentin452/Mo-Creatures-Continuation#19]
No idea why, but it says it came from an arrow, which is true (I tested ntm frag grenades), but the stacktrace points to Werewolf from mocreatures, and it happened at night when they also spawn. But line 162, indicated in the crash, is something related to getting itemstack, for comparison and causing damage, or something like that. The problem is also that for some reason I can't reproduce this crash.
Here's the crash report: https://mclo.gs/vWSDeWw#L5

**Comment by quentin452** [comment]
try using this : 
[DrZharks.MoCreatures.Mod.v6.4.1.zip](https://github.com/quentin452/Mo-Creatures-Continuation/files/13676194/DrZharks.MoCreatures.Mod.v6.4.1.zip)
need to be unzipped
