### ISSUE TITLE
Crash with Unknown mod(probably caused by a missing implementation of the Mo creatures menu)

### ISSUE THREAD

**Issue by Omgise** [quentin452/Mo-Creatures-Continuation#9]
[fml-client-latest.log](https://github.com/quentin452/Mo-Creatures-Continuation/files/13538993/fml-client-latest.log)

**Comment by quentin452** [comment]
for me the game do not crash with chococraft plus

**Comment by quentin452** [comment]
there is steps to get the bug?

**Comment by Omgise** [comment]
Of course, I'll do a video demonstration later

**Comment by Omgise** [comment]
Strange, I noticed that this bug is not triggered now

**Comment by quentin452** [comment]
do you have a crash report? or just a fml-client-latest.log

**Comment by Omgise** [comment]
[crash-2023-12-03_21.41.10-client.txt](https://github.com/quentin452/Mo-Creatures-Continuation/files/13539104/crash-2023-12-03_21.41.10-client.txt)

**Comment by quentin452** [comment]
it seem thats its a known issue ,some player have this crash

**Comment by Omgise** [comment]
Is it possible to fix it

**Comment by quentin452** [comment]
the problem is that , one player say , i got this crash when i open the mo creatures menu , but me i can't open the mo creatures menu , so i can't reproduce

**Comment by Omgise** [comment]
Well, maybe I'll look for steps to fully replicate the crash

**Comment by quentin452** [comment]
So i think the menu isn't implemented , so thats why the issue can appear , so l'ill error handling for it

**Comment by quentin452** [comment]
try V6.3.5 , this version shouldn't crash , it should just made errors in logs at the place of the crash

**Comment by Omgise** [comment]
[crash-2023-12-03_22.08.59-client.txt](https://github.com/quentin452/Mo-Creatures-Continuation/files/13539191/crash-2023-12-03_22.08.59-client.txt)

**Comment by quentin452** [comment]
redownload the jar

**Comment by quentin452** [comment]
or rename jar name to 
DrZharks.MoCreatures.Mod.v6.3.5

**Comment by Omgise** [comment]
ok

**Comment by Omgise** [comment]
It still crashes
[crash-2023-12-03_22.18.31-client.txt](https://github.com/quentin452/Mo-Creatures-Continuation/files/13539207/crash-2023-12-03_22.18.31-client.txt)

**Comment by quentin452** [comment]
Can you try adding GUIDE APi?

**Comment by Omgise** [comment]
Where do I download the GUIDE APi?

**Comment by quentin452** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/guide-api/files/2287184

**Comment by Omgise** [comment]
[crash-2023-12-03_22.42.50-client.txt](https://github.com/quentin452/Mo-Creatures-Continuation/files/13539271/crash-2023-12-03_22.42.50-client.txt)

**Comment by quentin452** [comment]
try this : unzip it
[DrZharks.MoCreatures.Mod.v6.3.6.zip](https://github.com/quentin452/Mo-Creatures-Continuation/files/13539285/DrZharks.MoCreatures.Mod.v6.3.6.zip)

**Comment by Omgise** [comment]
I feel a little sleepy now, I will try tomorrow when I have time

**Comment by Omgise** [comment]
The crash has been fixed, thanks!
